.TH NFACE "1" "June 2025" "Tom Scheers" "User Commands"
.SH NAME
nFace \- A simple camera interface through the terminal
.SH SYNOPSIS
.B nface [-h] [-l]
.SH DESCRIPTION
.TP
\fB\--help\fR 
show program usage and exit
.TP
\fB\--version, -v\fR 
show program version and exit
.TP
\fB\--height, -h\fR
set the height of the nface frame
.TP
\fB\--width, -w\fR
set the width of the nface frame
.TP
\fB\--increment, -i\fR
set the block increment to a specific value, the higher the faster the program runs, but the less accurate the picture will be
.TP
